# Generated by Django 5.1.6 on 2025-03-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_address_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="phone",
        ),
        migrations.AddField(
            model_name="address",
            name="comment",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Комментарий"
            ),
        ),
    ]
