services:

  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"

  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      retries: 50
      timeout: 5s
    restart: on-failure

  app:
    build: .
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    #      - static:/app/staticfiles
    #      - media:/app/media
    command: sh -c "./entrypoint.sh"
  #    stdin_open: true
  #    tty: true
  #    command: bash

  celery:
    build: .
    depends_on:
      - redis
      - db
      - app
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    command: celery -A config worker -l info

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/webroot:/var/www/certbot
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/webroot:/var/www/certbot
    command: >
      certonly --webroot -w /var/www/certbot 
      --email ${DOMAIN_ADMIN_EMAIL} 
      -d ${DOMAIN_NAME} -d www.${DOMAIN_NAME} -d flower.${DOMAIN_NAME} 
      --agree-tos --non-interactive
    depends_on:
      - nginx

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pg_admin:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  flower:
    build: .
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - celery
      - redis
    command: >
      celery -A config 
      --broker=${FLOWER_BROKER_URL}
      flower
      --port=${FLOWER_PORT}
      --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}


volumes:
  pg_data:
  pg_admin:
#  static:
#  media:
