# Generated by Django 5.2 on 2025-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tunes/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Инстаграм",
                "verbose_name_plural": "Инстаграм",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Почта"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Публиковать"),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TunesDict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=30, unique=True, verbose_name="Ключ"),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Строковое значение",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тонкие настройки",
                "verbose_name_plural": "Тонкие настройки",
                "ordering": ["key"],
            },
        ),
    ]
