# Generated by Django 5.1.6 on 2025-02-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                (
                    'content',
                    models.TextField(blank=True, null=True, verbose_name='Описание'),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='tunes/',
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(default=False, verbose_name='Активно'),
                ),
            ],
            options={
                'verbose_name': 'Заглавный баннер',
                'verbose_name_plural': 'Заглавные баннеры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.почта')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'is_published',
                    models.BooleanField(default=False, verbose_name='Активно'),
                ),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                (
                    'phone',
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name='Телефон'
                    ),
                ),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
                ),
                (
                    'is_read',
                    models.BooleanField(default=False, verbose_name='Прочитано'),
                ),
                (
                    'is_published',
                    models.BooleanField(default=False, verbose_name='Публиковать'),
                ),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('quote', models.TextField(blank=True, verbose_name='Цитата')),
                (
                    'is_published',
                    models.BooleanField(default=False, verbose_name='Публиковать'),
                ),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.CreateModel(
            name='TunesDict',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'key',
                    models.CharField(max_length=30, unique=True, verbose_name='Ключ'),
                ),
                (
                    'value_int',
                    models.CharField(
                        blank=True, null=True, verbose_name='Целочисленное значение'
                    ),
                ),
                (
                    'value_char',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Строковое значение',
                    ),
                ),
                (
                    'value_time',
                    models.TimeField(
                        blank=True, null=True, verbose_name='Константа времени'
                    ),
                ),
                (
                    'value_date',
                    models.DateField(
                        blank=True, null=True, verbose_name='Константа даты'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тонкие настройки',
                'verbose_name_plural': 'Тонкие настройки',
                'ordering': ['key'],
            },
        ),
    ]
