# Generated by Django 5.1.6 on 2025-02-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
