# Generated by Django 5.1.6 on 2025-03-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0002_delete_quote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tunesdict",
            old_name="value_char",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="tunesdict",
            name="value_date",
        ),
        migrations.RemoveField(
            model_name="tunesdict",
            name="value_int",
        ),
        migrations.RemoveField(
            model_name="tunesdict",
            name="value_time",
        ),
    ]
