# Generated by Django 5.1.6 on 2025-03-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0003_rename_value_char_tunesdict_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tunesdict",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Описание"
            ),
        ),
    ]
