# Generated by Django 5.1.6 on 2025-04-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0004_tunesdict_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "ordering": ["title"],
                "verbose_name": "Инстаграм",
                "verbose_name_plural": "Инстаграм",
            },
        ),
        migrations.RemoveField(
            model_name="banner",
            name="content",
        ),
    ]
