# Generated by Django 5.1.6 on 2025-04-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0005_alter_banner_options_remove_banner_content"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.AddField(
            model_name="feedback",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Почта"
            ),
        ),
    ]
