# Generated by Django 5.1.6 on 2025-04-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0006_delete_contact_feedback_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Телефон"),
        ),
    ]
