# Generated by Django 5.1.6 on 2025-04-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0007_alter_feedback_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["email"],
            },
        ),
    ]
