# Generated by Django 5.1.6 on 2025-04-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0008_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Почта"),
        ),
    ]
