# Generated by Django 5.1.6 on 2025-04-11 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0009_alter_subscriber_created_at_alter_subscriber_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={
                "ordering": ["email"],
                "verbose_name": "Адрес для рассылок",
                "verbose_name_plural": "Адреса для рассылок",
            },
        ),
        migrations.AddField(
            model_name="subscriber",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
            preserve_default=False,
        ),
    ]
