# Generated by Django 5.1.6 on 2025-04-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tunes", "0010_alter_subscriber_options_subscriber_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscriber",
        ),
    ]
