# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/toytales.ru
cert = /etc/letsencrypt/live/toytales.ru/cert.pem
privkey = /etc/letsencrypt/live/toytales.ru/privkey.pem
chain = /etc/letsencrypt/live/toytales.ru/chain.pem
fullchain = /etc/letsencrypt/live/toytales.ru/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d8d4bc7b7e1d453d882875b936417645
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
flower.toytales.ru = /var/www/certbot
toytales.ru = /var/www/certbot
www.toytales.ru = /var/www/certbot
