# Generated by Django 5.2 on 2025-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_test", models.BooleanField(default=True, verbose_name="Тест")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменена"),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Recipients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
            ],
            options={
                "verbose_name": "адрес для рассылок",
                "verbose_name_plural": "адреса для рассылок",
                "ordering": ["email"],
            },
        ),
    ]
