# Generated by Django 5.1.6 on 2025-04-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_test", models.BooleanField(default=True, verbose_name="")),
                ("text", models.TextField(verbose_name="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="subscribe",
            options={
                "ordering": ["email"],
                "verbose_name": "адрес для рассылок",
                "verbose_name_plural": "адреса для рассылок",
            },
        ),
    ]
