# Generated by Django 5.1.6 on 2025-04-12 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribes", "0002_article_alter_subscribe_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscribe",
            new_name="Recipients",
        ),
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.CharField(default=1, max_length=100, verbose_name="Заголовок"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_test",
            field=models.BooleanField(default=True, verbose_name="Тест"),
        ),
        migrations.AlterField(
            model_name="article",
            name="text",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменена"),
        ),
    ]
