# Generated by Django 5.1.6 on 2025-03-09 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blogarticle",
            name="users_like",
            field=models.ManyToManyField(
                blank=True, related_name="images_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
