# Generated by Django 5.1.6 on 2025-03-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogarticle_users_like"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.RemoveField(
            model_name="blogarticle",
            name="like_counter",
        ),
    ]
