# Generated by Django 5.2 on 2025-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Содержимое"),
        ),
    ]
