# Generated by Django 5.2 on 2025-04-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogarticle_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogarticle",
            name="short_descr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Краткое содержимое"
            ),
        ),
    ]
