# Generated by Django 5.1.6 on 2025-03-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comment_options_and_more"),
        ("dolls", "0007_alter_category_options_alter_image_options_and_more"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogarticle",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="dolls.category",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogarticle",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="tags_article",
                to="tags.tag",
                verbose_name="Теги",
            ),
        ),
    ]
