# Generated by Django 5.2 on 2025-04-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogarticle_short_descr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogarticle",
            old_name="short_descr",
            new_name="short_content",
        ),
    ]
