# Generated by Django 5.1.6 on 2025-03-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogarticle_category"),
        ("dolls", "0007_alter_category_options_alter_image_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="dolls.category",
                verbose_name="Категория",
            ),
        ),
    ]
