upstream django {
    server app:8000;
}

upstream flower {
    server flower:5555;
}

upstream pgadmin {
    server pgadmin:80;
}

server {
    listen 80;
    server_name toytales.ru www.toytales.ru flower.toytales.ru;

    client_max_body_size 20M;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }

}

server {
    listen 443 ssl;
    server_name toytales.ru www.toytales.ru;

    client_max_body_size 20M;

    ssl_certificate /etc/letsencrypt/live/toytales.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/toytales.ru/privkey.pem;

    location /pgadmin/ {
        proxy_pass http://pgadmin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Script-Name /pgadmin;
        proxy_cookie_path / /pgadmin/;
        proxy_redirect off;
    }

    location / {
        # Настройка X-Frame-Options для исключения Яндекса
        set $frame_options '';
        if ($http_referer !~ '^https?:\/\/([^\/]+\.)?(toytales\.ru|webvisor\.com|metri[ck]a\.yandex\.(com|ru|by|com\.tr))\/') {
            set $frame_options 'SAMEORIGIN';
        }
        add_header X-Frame-Options $frame_options;

        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/static/;
    }

    location /media/ {
        alias /app/media/;
    }
}

# Субдомен Flower
server {
    listen 443 ssl;
    server_name flower.toytales.ru;

    ssl_certificate /etc/letsencrypt/live/toytales.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/toytales.ru/privkey.pem;

    location / {
        proxy_pass http://flower/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

}
