# Generated by Django 5.2 on 2025-04-19 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Активно"),
                ),
                (
                    "active_on_main_page",
                    models.BooleanField(
                        default=False, verbose_name="Активно на гл.стр."
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Количество"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Старая цена"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменен"),
                ),
                (
                    "parameter",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Параметр"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Активно"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="dolls.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tags_product",
                        to="tags.tag",
                        verbose_name="Теги",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="upload/product_images", verbose_name="Фото"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Активно"),
                ),
                (
                    "active_on_main_page",
                    models.BooleanField(
                        default=False, verbose_name="Активно на гл.стр."
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dolls.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
                "ordering": ["name"],
            },
        ),
    ]
