# Generated by Django 5.2 on 2025-04-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dolls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
