# Generated by Django 5.1.6 on 2025-02-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Имя'
            ),
        ),
    ]
