# Generated by Django 5.1.6 on 2025-02-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolls', '0002_alter_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name='Старая цена'
            ),
            preserve_default=False,
        ),
    ]
