# Generated by Django 5.2 on 2025-04-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dolls", "0002_product_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Краткое описание"
            ),
        ),
    ]
