# Generated by Django 5.1.6 on 2025-02-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolls', '0003_product_old_price'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name='tags',
                to='tags.tag',
                verbose_name='Теги',
            ),
        ),
    ]
