# Generated by Django 5.1.6 on 2025-02-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolls', '0005_alter_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='Количество'
            ),
        ),
    ]
