# Generated by Django 5.1.6 on 2025-03-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dolls", "0006_product_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ["name"],
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
