# Generated by Django 5.1.6 on 2025-04-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dolls", "0007_alter_category_options_alter_image_options_and_more"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="tags_product",
                to="tags.tag",
                verbose_name="Теги",
            ),
        ),
    ]
