# Generated by Django 5.1.6 on 2025-03-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="zip",
            new_name="postal_code",
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(
                default=1212, max_length=254, verbose_name="Эл.почта"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(default=1212, max_length=50, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(
                default=121212, max_length=50, verbose_name="Фамилия"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Отчество"
            ),
        ),
    ]
