# Generated by Django 5.1.6 on 2025-04-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_rename_zip_order_postal_code_order_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создан"),
                    ("NONPAID", "К оплате"),
                    ("PAID", "Оплачен"),
                    ("SEND", "Отправлен"),
                    ("SHIPPED", "Доставлен"),
                ],
                default="CREATED",
                max_length=10,
            ),
        ),
    ]
